### PR TITLE
feat: link in stay light on active

### LINKED ISSUE #75: Make the link in the navbar stay light cerise on the active page

### PR DESCRIPTION
**Pull request by Poizon7**
Fixes https://github.com/datasektionen/bawang/issues/75

### CODE REVIEW

**Review by Benjaneb — APPROVED** [review]
LGTM!

**Comment by foodelevator** [comment]
It would be nice if for example the "Nämnder" button would still be active if you're on e.g. `/namnder/informationsorganet`

**Comment by foodelevator** [comment]
This, or more specifically:
```
/app/node_modules/methone/dist/components/TopBar.js:183
  className: window.location.pathname === link.props.to && "current",
             ^

ReferenceError: window is not defined
```
made bawang crash on start when dependabot updated express (not sure why it happened now).

Methone is also server-rendered, which is why `window` doesn't always exist. Not sure how to solve this in a nice way.

**Comment by foodelevator** [comment]
@Benjaneb @WALLE-AXIOM

**Pull request merged**
